### ISSUE TITLE
항공편

### ISSUE THREAD

**Issue by LimJaeYong** [LimJaeYong/Sapporo#1]
비행기 예매시기에 대해
얼마까지 내려가면 바로 예매할까
1/3~10 현재 45만

**Comment by LimJaeYong** [comment]
올 때 후쿠오카 경유
45만
https://www.skyscanner.co.kr/transport/flights/icn/cts/230103/230110/config/12409-2301030835--32161-0-10783-2301031115%7C10783-2301101405--32184,-32179-1-12409-2301102015?adultsv2=3&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&rtn=1

**Comment by wlgns4935** [comment]
40까지는 안내려가겠죠?

**Comment by Jung-H-C** [comment]
사딸라 ㄱ

**Comment by LimJaeYong** [comment]
경유면 6시간은 걸리는데 ㄱㅊ?

**Comment by Jung-H-C** [comment]
사딸라 ㄱ

**Comment by LimJaeYong** [comment]
11일 복귀 48만
https://www.skyscanner.co.kr/transport/flights/icn/cts/230103/230111/config/12409-2301030835--32161-0-10783-2301031115%7C10783-2301111555--32179-0-12409-2301111910?adultsv2=3&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&rtn=1

**Comment by LimJaeYong** [comment]
> 올 때 후쿠오카 경유 45만 https://www.skyscanner.co.kr/transport/flights/icn/cts/230103/230110/config/12409-2301030835--32161-0-10783-2301031115%7C10783-2301101405--32184,-32179-1-12409-2301102015?adultsv2=3&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&rtn=1

페이지 삭제됐어요
